version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      #maps local host port of api gateway to container api gateway 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - library-service
    networks:
      - readx-network

  library-service:
    build:
      context: ./library-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - readx-network

networks:
  readx-network:
    driver: bridge 