version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      #maps local host port of api gateway to container api gateway 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LIBRARY_SERVICE_HOST=library-service
      - LIBRARY_SERVICE_PORT=3001
    depends_on:
      - library-service
    networks:
      - readx-network

  library-service:
    build:
      context: ./library-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=library_db
    depends_on:
      - postgres
    networks:
      - readx-network

  tracker-service:
    build:
      context: ./tracker-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DB_HOST=tracker-postgres
      - DB_PORT=5432
      - DB_USERNAME=tracker_user
      - DB_PASSWORD=tracker_password
      - DB_DATABASE=tracker_db
    depends_on:
      - tracker-postgres
    networks:
      - readx-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - readx-network

  tracker-postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=tracker_user
      - POSTGRES_PASSWORD=tracker_password
      - POSTGRES_DB=tracker_db
    volumes:
      - tracker_postgres_data:/var/lib/postgresql/data
    networks:
      - readx-network

networks:
  readx-network:
    driver: bridge

volumes:
  postgres_data:
  tracker_postgres_data: 